name: dart_learn
description: Samples of coding in Dart.
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  test: ^1.0.0




